# .readthedocs.yaml

version: 2

# Build documentation in the "docs" directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Define the Python version and environment for building the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
      version: 3.11
      install:
        - requirements: requirements.txt
        - method: pip
          path: .

# Optionally specify the branch to build the documentation from
# Uncomment the following lines to build only from 'master' branch
branches:
  only:
    - master

# Add any specific settings you need for Django
django:
  settings: oc_lettings_site.settings
  migrate: true

# Remove the build section completely if it's not needed
# The following section has been removed:
# build:
#   commands:
#     - sphinx-build -b html docs/ _build/html
