# .readthedocs.yaml

version: 2

# Build documentation in the "docs" directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Define the Python version and environment for building the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Add the install commands separately
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

# Add any specific settings you need for Django
django:
  settings: oc_lettings_site.settings
  migrate: true

# Remove the build section completely if it's not needed
# The following section has been removed:
# build:
#   commands:
#     - sphinx-build -b html docs/ _build/html
